from pages.mainapp import about_page
from pages.mainapp import tutorials_page
from pages.mainapp import glossary_page
from pages.mainapp import home_page
from pages.mainapp import meta_data_page
from pages.mainapp import search_page
from pages.mainapp import citations_page
from pages.mainapp import login_page
from pages.individual import gene_info_page
from pages.individual import mirna_info_page
from pages.individual import rna_type_page
from pages.individual import spatial_info_page
from pages.individual import ppi_info_page
from pages.individual import go_info_page
from pages.individual import local_info_page
from pages.individual import orthologs_info_page
from pages.individual import snp_info_page
from pages.individual import primer_info_page
